# registry-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: local-registry
  namespace: default
spec:
  ports:
    - port: 5005
      targetPort: 5005
---
apiVersion: v1
kind: Endpoints
metadata:
  name: local-registry
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.182
    ports:
      - port: 5005
